/* A Bison parser, made by GNU Bison 3.8.2.  */

/* Bison implementation for Yacc-like parsers in C

   Copyright (C) 1984, 1989-1990, 2000-2015, 2018-2021 Free Software Foundation,
   Inc.

   This program is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program.  If not, see <https://www.gnu.org/licenses/>.  */

/* As a special exception, you may create a larger work that contains
   part or all of the Bison parser skeleton and distribute that work
   under terms of your choice, so long as that work isn't itself a
   parser generator using the skeleton or a modified version thereof
   as a parser skeleton.  Alternatively, if you modify or redistribute
   the parser skeleton itself, you may (at your option) remove this
   special exception, which will cause the skeleton and the resulting
   Bison output files to be licensed under the GNU General Public
   License without this special exception.

   This special exception was added by the Free Software Foundation in
   version 2.2 of Bison.  */

/* C LALR(1) parser skeleton written by Richard Stallman, by
   simplifying the original so-called "semantic" parser.  */

/* DO NOT RELY ON FEATURES THAT ARE NOT DOCUMENTED in the manual,
   especially those whose name start with YY_ or yy_.  They are
   private implementation details that can be changed or removed.  */

/* All symbols defined below should begin with yy or YY, to avoid
   infringing on user name space.  This should be done even for local
   variables, as they might otherwise be expanded by user macros.
   There are some unavoidable exceptions within include files to
   define necessary library symbols; they are noted "INFRINGES ON
   USER NAME SPACE" below.  */

/* Identify Bison output, and Bison version.  */
#define YYBISON 30802

/* Bison version string.  */
#define YYBISON_VERSION "3.8.2"

/* Skeleton name.  */
#define YYSKELETON_NAME "yacc.c"

/* Pure parsers.  */
#define YYPURE 0

/* Push parsers.  */
#define YYPUSH 0

/* Pull parsers.  */
#define YYPULL 1




/* First part of user prologue.  */
#line 1 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"

#include <cstdio>
#include <cstring>

// 词法分析头文件
#include "FlexLexer.h"

// bison生成的头文件
#include "BisonParser.h"

// 抽象语法树函数定义原型头文件
#include "AST.h"

#include "IntegerType.h"
#include "VoidType.h"
#include "PointerType.h"

// LR分析失败时所调用函数的原型声明
void yyerror(char * msg);


#line 93 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"

# ifndef YY_CAST
#  ifdef __cplusplus
#   define YY_CAST(Type, Val) static_cast<Type> (Val)
#   define YY_REINTERPRET_CAST(Type, Val) reinterpret_cast<Type> (Val)
#  else
#   define YY_CAST(Type, Val) ((Type) (Val))
#   define YY_REINTERPRET_CAST(Type, Val) ((Type) (Val))
#  endif
# endif
# ifndef YY_NULLPTR
#  if defined __cplusplus
#   if 201103L <= __cplusplus
#    define YY_NULLPTR nullptr
#   else
#    define YY_NULLPTR 0
#   endif
#  else
#   define YY_NULLPTR ((void*)0)
#  endif
# endif

#include "MiniCBison.h"
/* Symbol kind.  */
enum yysymbol_kind_t
{
  YYSYMBOL_YYEMPTY = -2,
  YYSYMBOL_YYEOF = 0,                      /* "end of file"  */
  YYSYMBOL_YYerror = 1,                    /* error  */
  YYSYMBOL_YYUNDEF = 2,                    /* "invalid token"  */
  YYSYMBOL_T_DIGIT = 3,                    /* T_DIGIT  */
  YYSYMBOL_T_ID = 4,                       /* T_ID  */
  YYSYMBOL_T_INT = 5,                      /* T_INT  */
  YYSYMBOL_T_VOID = 6,                     /* T_VOID  */
  YYSYMBOL_T_RETURN = 7,                   /* T_RETURN  */
  YYSYMBOL_T_IF = 8,                       /* T_IF  */
  YYSYMBOL_T_ELSE = 9,                     /* T_ELSE  */
  YYSYMBOL_T_WHILE = 10,                   /* T_WHILE  */
  YYSYMBOL_T_FOR = 11,                     /* T_FOR  */
  YYSYMBOL_T_BREAK = 12,                   /* T_BREAK  */
  YYSYMBOL_T_CONTINUE = 13,                /* T_CONTINUE  */
  YYSYMBOL_T_GE = 14,                      /* T_GE  */
  YYSYMBOL_T_GT = 15,                      /* T_GT  */
  YYSYMBOL_T_LE = 16,                      /* T_LE  */
  YYSYMBOL_T_LT = 17,                      /* T_LT  */
  YYSYMBOL_T_EQ = 18,                      /* T_EQ  */
  YYSYMBOL_T_NE = 19,                      /* T_NE  */
  YYSYMBOL_T_AND = 20,                     /* T_AND  */
  YYSYMBOL_T_OR = 21,                      /* T_OR  */
  YYSYMBOL_T_NOT = 22,                     /* T_NOT  */
  YYSYMBOL_T_SEMICOLON = 23,               /* T_SEMICOLON  */
  YYSYMBOL_T_L_PAREN = 24,                 /* T_L_PAREN  */
  YYSYMBOL_T_R_PAREN = 25,                 /* T_R_PAREN  */
  YYSYMBOL_T_L_BRACE = 26,                 /* T_L_BRACE  */
  YYSYMBOL_T_R_BRACE = 27,                 /* T_R_BRACE  */
  YYSYMBOL_T_L_BRACKET = 28,               /* T_L_BRACKET  */
  YYSYMBOL_T_R_BRACKET = 29,               /* T_R_BRACKET  */
  YYSYMBOL_T_COMMA = 30,                   /* T_COMMA  */
  YYSYMBOL_T_ASSIGN = 31,                  /* T_ASSIGN  */
  YYSYMBOL_T_SUB = 32,                     /* T_SUB  */
  YYSYMBOL_T_ADD = 33,                     /* T_ADD  */
  YYSYMBOL_T_MUL = 34,                     /* T_MUL  */
  YYSYMBOL_T_DIV = 35,                     /* T_DIV  */
  YYSYMBOL_T_MOD = 36,                     /* T_MOD  */
  YYSYMBOL_YYACCEPT = 37,                  /* $accept  */
  YYSYMBOL_CompileUnit = 38,               /* CompileUnit  */
  YYSYMBOL_FuncDef = 39,                   /* FuncDef  */
  YYSYMBOL_FormalParams = 40,              /* FormalParams  */
  YYSYMBOL_FormalParamList = 41,           /* FormalParamList  */
  YYSYMBOL_FormalParam = 42,               /* FormalParam  */
  YYSYMBOL_DimensionList = 43,             /* DimensionList  */
  YYSYMBOL_IndexList = 44,                 /* IndexList  */
  YYSYMBOL_Block = 45,                     /* Block  */
  YYSYMBOL_BlockItemList = 46,             /* BlockItemList  */
  YYSYMBOL_BlockItem = 47,                 /* BlockItem  */
  YYSYMBOL_VarDecl = 48,                   /* VarDecl  */
  YYSYMBOL_VarDeclExpr = 49,               /* VarDeclExpr  */
  YYSYMBOL_VarDef = 50,                    /* VarDef  */
  YYSYMBOL_BasicType = 51,                 /* BasicType  */
  YYSYMBOL_Statement = 52,                 /* Statement  */
  YYSYMBOL_Expr = 53,                      /* Expr  */
  YYSYMBOL_LogicalOrExp = 54,              /* LogicalOrExp  */
  YYSYMBOL_LogicalAndExp = 55,             /* LogicalAndExp  */
  YYSYMBOL_RelExp = 56,                    /* RelExp  */
  YYSYMBOL_AddExp = 57,                    /* AddExp  */
  YYSYMBOL_MulExp = 58,                    /* MulExp  */
  YYSYMBOL_AddOp = 59,                     /* AddOp  */
  YYSYMBOL_MulOp = 60,                     /* MulOp  */
  YYSYMBOL_UnaryOp = 61,                   /* UnaryOp  */
  YYSYMBOL_UnaryExp = 62,                  /* UnaryExp  */
  YYSYMBOL_PrimaryExp = 63,                /* PrimaryExp  */
  YYSYMBOL_RealParamList = 64,             /* RealParamList  */
  YYSYMBOL_LVal = 65                       /* LVal  */
};
typedef enum yysymbol_kind_t yysymbol_kind_t;




#ifdef short
# undef short
#endif

/* On compilers that do not define __PTRDIFF_MAX__ etc., make sure
   <limits.h> and (if available) <stdint.h> are included
   so that the code can choose integer types of a good width.  */

#ifndef __PTRDIFF_MAX__
# include <limits.h> /* INFRINGES ON USER NAME SPACE */
# if defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stdint.h> /* INFRINGES ON USER NAME SPACE */
#  define YY_STDINT_H
# endif
#endif

/* Narrow types that promote to a signed type and that can represent a
   signed or unsigned integer of at least N bits.  In tables they can
   save space and decrease cache pressure.  Promoting to a signed type
   helps avoid bugs in integer arithmetic.  */

#ifdef __INT_LEAST8_MAX__
typedef __INT_LEAST8_TYPE__ yytype_int8;
#elif defined YY_STDINT_H
typedef int_least8_t yytype_int8;
#else
typedef signed char yytype_int8;
#endif

#ifdef __INT_LEAST16_MAX__
typedef __INT_LEAST16_TYPE__ yytype_int16;
#elif defined YY_STDINT_H
typedef int_least16_t yytype_int16;
#else
typedef short yytype_int16;
#endif

/* Work around bug in HP-UX 11.23, which defines these macros
   incorrectly for preprocessor constants.  This workaround can likely
   be removed in 2023, as HPE has promised support for HP-UX 11.23
   (aka HP-UX 11i v2) only through the end of 2022; see Table 2 of
   <https://h20195.www2.hpe.com/V2/getpdf.aspx/4AA4-7673ENW.pdf>.  */
#ifdef __hpux
# undef UINT_LEAST8_MAX
# undef UINT_LEAST16_MAX
# define UINT_LEAST8_MAX 255
# define UINT_LEAST16_MAX 65535
#endif

#if defined __UINT_LEAST8_MAX__ && __UINT_LEAST8_MAX__ <= __INT_MAX__
typedef __UINT_LEAST8_TYPE__ yytype_uint8;
#elif (!defined __UINT_LEAST8_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST8_MAX <= INT_MAX)
typedef uint_least8_t yytype_uint8;
#elif !defined __UINT_LEAST8_MAX__ && UCHAR_MAX <= INT_MAX
typedef unsigned char yytype_uint8;
#else
typedef short yytype_uint8;
#endif

#if defined __UINT_LEAST16_MAX__ && __UINT_LEAST16_MAX__ <= __INT_MAX__
typedef __UINT_LEAST16_TYPE__ yytype_uint16;
#elif (!defined __UINT_LEAST16_MAX__ && defined YY_STDINT_H \
       && UINT_LEAST16_MAX <= INT_MAX)
typedef uint_least16_t yytype_uint16;
#elif !defined __UINT_LEAST16_MAX__ && USHRT_MAX <= INT_MAX
typedef unsigned short yytype_uint16;
#else
typedef int yytype_uint16;
#endif

#ifndef YYPTRDIFF_T
# if defined __PTRDIFF_TYPE__ && defined __PTRDIFF_MAX__
#  define YYPTRDIFF_T __PTRDIFF_TYPE__
#  define YYPTRDIFF_MAXIMUM __PTRDIFF_MAX__
# elif defined PTRDIFF_MAX
#  ifndef ptrdiff_t
#   include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  endif
#  define YYPTRDIFF_T ptrdiff_t
#  define YYPTRDIFF_MAXIMUM PTRDIFF_MAX
# else
#  define YYPTRDIFF_T long
#  define YYPTRDIFF_MAXIMUM LONG_MAX
# endif
#endif

#ifndef YYSIZE_T
# ifdef __SIZE_TYPE__
#  define YYSIZE_T __SIZE_TYPE__
# elif defined size_t
#  define YYSIZE_T size_t
# elif defined __STDC_VERSION__ && 199901 <= __STDC_VERSION__
#  include <stddef.h> /* INFRINGES ON USER NAME SPACE */
#  define YYSIZE_T size_t
# else
#  define YYSIZE_T unsigned
# endif
#endif

#define YYSIZE_MAXIMUM                                  \
  YY_CAST (YYPTRDIFF_T,                                 \
           (YYPTRDIFF_MAXIMUM < YY_CAST (YYSIZE_T, -1)  \
            ? YYPTRDIFF_MAXIMUM                         \
            : YY_CAST (YYSIZE_T, -1)))

#define YYSIZEOF(X) YY_CAST (YYPTRDIFF_T, sizeof (X))


/* Stored state numbers (used for stacks). */
typedef yytype_uint8 yy_state_t;

/* State numbers in computations.  */
typedef int yy_state_fast_t;

#ifndef YY_
# if defined YYENABLE_NLS && YYENABLE_NLS
#  if ENABLE_NLS
#   include <libintl.h> /* INFRINGES ON USER NAME SPACE */
#   define YY_(Msgid) dgettext ("bison-runtime", Msgid)
#  endif
# endif
# ifndef YY_
#  define YY_(Msgid) Msgid
# endif
#endif


#ifndef YY_ATTRIBUTE_PURE
# if defined __GNUC__ && 2 < __GNUC__ + (96 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_PURE __attribute__ ((__pure__))
# else
#  define YY_ATTRIBUTE_PURE
# endif
#endif

#ifndef YY_ATTRIBUTE_UNUSED
# if defined __GNUC__ && 2 < __GNUC__ + (7 <= __GNUC_MINOR__)
#  define YY_ATTRIBUTE_UNUSED __attribute__ ((__unused__))
# else
#  define YY_ATTRIBUTE_UNUSED
# endif
#endif

/* Suppress unused-variable warnings by "using" E.  */
#if ! defined lint || defined __GNUC__
# define YY_USE(E) ((void) (E))
#else
# define YY_USE(E) /* empty */
#endif

/* Suppress an incorrect diagnostic about yylval being uninitialized.  */
#if defined __GNUC__ && ! defined __ICC && 406 <= __GNUC__ * 100 + __GNUC_MINOR__
# if __GNUC__ * 100 + __GNUC_MINOR__ < 407
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")
# else
#  define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN                           \
    _Pragma ("GCC diagnostic push")                                     \
    _Pragma ("GCC diagnostic ignored \"-Wuninitialized\"")              \
    _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")
# endif
# define YY_IGNORE_MAYBE_UNINITIALIZED_END      \
    _Pragma ("GCC diagnostic pop")
#else
# define YY_INITIAL_VALUE(Value) Value
#endif
#ifndef YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
# define YY_IGNORE_MAYBE_UNINITIALIZED_END
#endif
#ifndef YY_INITIAL_VALUE
# define YY_INITIAL_VALUE(Value) /* Nothing. */
#endif

#if defined __cplusplus && defined __GNUC__ && ! defined __ICC && 6 <= __GNUC__
# define YY_IGNORE_USELESS_CAST_BEGIN                          \
    _Pragma ("GCC diagnostic push")                            \
    _Pragma ("GCC diagnostic ignored \"-Wuseless-cast\"")
# define YY_IGNORE_USELESS_CAST_END            \
    _Pragma ("GCC diagnostic pop")
#endif
#ifndef YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_BEGIN
# define YY_IGNORE_USELESS_CAST_END
#endif


#define YY_ASSERT(E) ((void) (0 && (E)))

#if !defined yyoverflow

/* The parser invokes alloca or malloc; define the necessary symbols.  */

# ifdef YYSTACK_USE_ALLOCA
#  if YYSTACK_USE_ALLOCA
#   ifdef __GNUC__
#    define YYSTACK_ALLOC __builtin_alloca
#   elif defined __BUILTIN_VA_ARG_INCR
#    include <alloca.h> /* INFRINGES ON USER NAME SPACE */
#   elif defined _AIX
#    define YYSTACK_ALLOC __alloca
#   elif defined _MSC_VER
#    include <malloc.h> /* INFRINGES ON USER NAME SPACE */
#    define alloca _alloca
#   else
#    define YYSTACK_ALLOC alloca
#    if ! defined _ALLOCA_H && ! defined EXIT_SUCCESS
#     include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
      /* Use EXIT_SUCCESS as a witness for stdlib.h.  */
#     ifndef EXIT_SUCCESS
#      define EXIT_SUCCESS 0
#     endif
#    endif
#   endif
#  endif
# endif

# ifdef YYSTACK_ALLOC
   /* Pacify GCC's 'empty if-body' warning.  */
#  define YYSTACK_FREE(Ptr) do { /* empty */; } while (0)
#  ifndef YYSTACK_ALLOC_MAXIMUM
    /* The OS might guarantee only one guard page at the bottom of the stack,
       and a page size can be as small as 4096 bytes.  So we cannot safely
       invoke alloca (N) if N exceeds 4096.  Use a slightly smaller number
       to allow for a few compiler-allocated temporary stack slots.  */
#   define YYSTACK_ALLOC_MAXIMUM 4032 /* reasonable circa 2006 */
#  endif
# else
#  define YYSTACK_ALLOC YYMALLOC
#  define YYSTACK_FREE YYFREE
#  ifndef YYSTACK_ALLOC_MAXIMUM
#   define YYSTACK_ALLOC_MAXIMUM YYSIZE_MAXIMUM
#  endif
#  if (defined __cplusplus && ! defined EXIT_SUCCESS \
       && ! ((defined YYMALLOC || defined malloc) \
             && (defined YYFREE || defined free)))
#   include <stdlib.h> /* INFRINGES ON USER NAME SPACE */
#   ifndef EXIT_SUCCESS
#    define EXIT_SUCCESS 0
#   endif
#  endif
#  ifndef YYMALLOC
#   define YYMALLOC malloc
#   if ! defined malloc && ! defined EXIT_SUCCESS
void *malloc (YYSIZE_T); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
#  ifndef YYFREE
#   define YYFREE free
#   if ! defined free && ! defined EXIT_SUCCESS
void free (void *); /* INFRINGES ON USER NAME SPACE */
#   endif
#  endif
# endif
#endif /* !defined yyoverflow */

#if (! defined yyoverflow \
     && (! defined __cplusplus \
         || (defined YYSTYPE_IS_TRIVIAL && YYSTYPE_IS_TRIVIAL)))

/* A type that is properly aligned for any stack member.  */
union yyalloc
{
  yy_state_t yyss_alloc;
  YYSTYPE yyvs_alloc;
};

/* The size of the maximum gap between one aligned stack and the next.  */
# define YYSTACK_GAP_MAXIMUM (YYSIZEOF (union yyalloc) - 1)

/* The size of an array large to enough to hold all stacks, each with
   N elements.  */
# define YYSTACK_BYTES(N) \
     ((N) * (YYSIZEOF (yy_state_t) + YYSIZEOF (YYSTYPE)) \
      + YYSTACK_GAP_MAXIMUM)

# define YYCOPY_NEEDED 1

/* Relocate STACK from its old location to the new one.  The
   local variables YYSIZE and YYSTACKSIZE give the old and new number of
   elements in the stack, and YYPTR gives the new location of the
   stack.  Advance YYPTR to a properly aligned location for the next
   stack.  */
# define YYSTACK_RELOCATE(Stack_alloc, Stack)                           \
    do                                                                  \
      {                                                                 \
        YYPTRDIFF_T yynewbytes;                                         \
        YYCOPY (&yyptr->Stack_alloc, Stack, yysize);                    \
        Stack = &yyptr->Stack_alloc;                                    \
        yynewbytes = yystacksize * YYSIZEOF (*Stack) + YYSTACK_GAP_MAXIMUM; \
        yyptr += yynewbytes / YYSIZEOF (*yyptr);                        \
      }                                                                 \
    while (0)

#endif

#if defined YYCOPY_NEEDED && YYCOPY_NEEDED
/* Copy COUNT objects from SRC to DST.  The source and destination do
   not overlap.  */
# ifndef YYCOPY
#  if defined __GNUC__ && 1 < __GNUC__
#   define YYCOPY(Dst, Src, Count) \
      __builtin_memcpy (Dst, Src, YY_CAST (YYSIZE_T, (Count)) * sizeof (*(Src)))
#  else
#   define YYCOPY(Dst, Src, Count)              \
      do                                        \
        {                                       \
          YYPTRDIFF_T yyi;                      \
          for (yyi = 0; yyi < (Count); yyi++)   \
            (Dst)[yyi] = (Src)[yyi];            \
        }                                       \
      while (0)
#  endif
# endif
#endif /* !YYCOPY_NEEDED */

/* YYFINAL -- State number of the termination state.  */
#define YYFINAL  8
/* YYLAST -- Last index in YYTABLE.  */
#define YYLAST   173

/* YYNTOKENS -- Number of terminals.  */
#define YYNTOKENS  37
/* YYNNTS -- Number of nonterminals.  */
#define YYNNTS  29
/* YYNRULES -- Number of rules.  */
#define YYNRULES  78
/* YYNSTATES -- Number of states.  */
#define YYNSTATES  143

/* YYMAXUTOK -- Last valid token kind.  */
#define YYMAXUTOK   291


/* YYTRANSLATE(TOKEN-NUM) -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex, with out-of-bounds checking.  */
#define YYTRANSLATE(YYX)                                \
  (0 <= (YYX) && (YYX) <= YYMAXUTOK                     \
   ? YY_CAST (yysymbol_kind_t, yytranslate[YYX])        \
   : YYSYMBOL_YYUNDEF)

/* YYTRANSLATE[TOKEN-NUM] -- Symbol number corresponding to TOKEN-NUM
   as returned by yylex.  */
static const yytype_int8 yytranslate[] =
{
       0,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
       2,     2,     2,     2,     2,     2,     1,     2,     3,     4,
       5,     6,     7,     8,     9,    10,    11,    12,    13,    14,
      15,    16,    17,    18,    19,    20,    21,    22,    23,    24,
      25,    26,    27,    28,    29,    30,    31,    32,    33,    34,
      35,    36
};

#if YYDEBUG
/* YYRLINE[YYN] -- Source line where rule number YYN was defined.  */
static const yytype_int16 yyrline[] =
{
       0,    83,    83,    91,    97,   102,   109,   126,   145,   149,
     156,   160,   167,   182,   212,   217,   222,   229,   233,   242,
     248,   259,   264,   273,   277,   288,   294,   306,   320,   328,
     345,   360,   363,   374,   377,   381,   384,   387,   390,   394,
     397,   400,   403,   406,   409,   416,   421,   424,   429,   432,
     437,   440,   443,   446,   449,   452,   455,   465,   466,   470,
     471,   474,   477,   481,   482,   483,   486,   487,   493,   499,
     515,   534,   538,   544,   550,   559,   563,   570,   579
};
#endif

/** Accessing symbol of state STATE.  */
#define YY_ACCESSING_SYMBOL(State) YY_CAST (yysymbol_kind_t, yystos[State])

#if YYDEBUG || 0
/* The user-facing name of the symbol whose (internal) number is
   YYSYMBOL.  No bounds checking.  */
static const char *yysymbol_name (yysymbol_kind_t yysymbol) YY_ATTRIBUTE_UNUSED;

/* YYTNAME[SYMBOL-NUM] -- String name of the symbol SYMBOL-NUM.
   First, the terminals, then, starting at YYNTOKENS, nonterminals.  */
static const char *const yytname[] =
{
  "\"end of file\"", "error", "\"invalid token\"", "T_DIGIT", "T_ID",
  "T_INT", "T_VOID", "T_RETURN", "T_IF", "T_ELSE", "T_WHILE", "T_FOR",
  "T_BREAK", "T_CONTINUE", "T_GE", "T_GT", "T_LE", "T_LT", "T_EQ", "T_NE",
  "T_AND", "T_OR", "T_NOT", "T_SEMICOLON", "T_L_PAREN", "T_R_PAREN",
  "T_L_BRACE", "T_R_BRACE", "T_L_BRACKET", "T_R_BRACKET", "T_COMMA",
  "T_ASSIGN", "T_SUB", "T_ADD", "T_MUL", "T_DIV", "T_MOD", "$accept",
  "CompileUnit", "FuncDef", "FormalParams", "FormalParamList",
  "FormalParam", "DimensionList", "IndexList", "Block", "BlockItemList",
  "BlockItem", "VarDecl", "VarDeclExpr", "VarDef", "BasicType",
  "Statement", "Expr", "LogicalOrExp", "LogicalAndExp", "RelExp", "AddExp",
  "MulExp", "AddOp", "MulOp", "UnaryOp", "UnaryExp", "PrimaryExp",
  "RealParamList", "LVal", YY_NULLPTR
};

static const char *
yysymbol_name (yysymbol_kind_t yysymbol)
{
  return yytname[yysymbol];
}
#endif

#define YYPACT_NINF (-44)

#define yypact_value_is_default(Yyn) \
  ((Yyn) == YYPACT_NINF)

#define YYTABLE_NINF (-1)

#define yytable_value_is_error(Yyn) \
  0

/* YYPACT[STATE-NUM] -- Index in YYTABLE of the portion describing
   STATE-NUM.  */
static const yytype_int16 yypact[] =
{
      80,   -44,   -44,    78,   -44,   -44,   -10,     0,   -44,   -44,
     -44,   -44,     8,   -22,   -44,    35,   -44,    39,    37,   111,
      30,    42,    55,    74,   -44,   103,    83,   -44,    22,   -44,
     111,   -44,   -44,   102,   105,   122,    63,    82,   111,   -44,
     -44,   -44,   123,    11,   -44,    42,    80,    99,   -44,    45,
     111,   100,   104,   111,   111,   111,   111,   111,   111,   111,
     111,   -44,   -44,   111,   -44,   -44,   -44,   111,   -44,   113,
       4,   107,   108,   110,   127,   128,   -44,   -44,   -44,    49,
     -44,   -44,     8,   -44,   129,   124,   -44,   -44,   125,   -44,
     -44,    17,   130,   111,   -44,   105,   122,    63,    63,    63,
      63,    63,    63,    82,   -44,   -44,   -44,   133,   111,   111,
     111,   -44,   -44,   -44,   -44,   -44,   111,   132,   -44,   111,
     -44,   134,   -44,   136,   137,   135,   141,    30,   -44,   -44,
      98,    98,   111,   -44,   144,   -44,   142,    98,   111,   -44,
     143,    98,   -44
};

/* YYDEFACT[STATE-NUM] -- Default reduction number in state STATE-NUM.
   Performed when YYTABLE does not specify something else to do.  Zero
   means the default is an error.  */
static const yytype_int8 yydefact[] =
{
       0,    31,    32,     0,     2,     3,     0,     0,     1,     4,
       5,    25,     0,    16,    26,    16,    27,     0,     0,     0,
      29,     0,     0,     9,    10,     0,     0,    72,    77,    67,
       0,    66,    30,    45,    46,    48,    50,    57,     0,    59,
      68,    73,     0,     0,     6,     0,     0,    12,    14,     0,
       0,    78,     0,     0,     0,     0,     0,     0,     0,     0,
       0,    62,    61,     0,    63,    64,    65,     0,    74,     0,
       0,     0,     0,     0,     0,     0,    38,    19,    36,     0,
      21,    24,     0,    23,     0,    73,     7,    11,     0,    69,
      75,     0,     0,     0,    71,    47,    49,    53,    51,    54,
      52,    55,    56,    58,    60,    15,    34,     0,     0,     0,
       0,    43,    44,    20,    22,    37,     0,    16,    70,     0,
      17,     0,    33,     0,     0,     0,     0,    13,    76,    18,
       0,     0,     0,    35,    39,    41,     0,     0,     0,    40,
       0,     0,    42
};

/* YYPGOTO[NTERM-NUM].  */
static const yytype_int16 yypgoto[] =
{
     -44,   -44,   154,   -44,   -44,   120,    50,   -44,   -20,   -44,
      90,    79,   -44,   158,   -14,   -43,   -19,   -44,   118,   119,
      89,   109,   -44,   -44,   -44,   -28,   -44,   -44,   -38
};

/* YYDEFGOTO[NTERM-NUM].  */
static const yytype_int8 yydefgoto[] =
{
       0,     3,     4,    22,    23,    24,    20,    51,    78,    79,
      80,    81,     6,    14,     7,    83,    84,    33,    34,    35,
      36,    37,    63,    67,    38,    39,    40,    91,    41
};

/* YYTABLE[YYPACT[STATE-NUM]] -- What to do in state STATE-NUM.  If
   positive, shift that token.  If negative, reduce the rule whose
   number is the opposite.  If YYTABLE_NINF, syntax error.  */
static const yytype_uint8 yytable[] =
{
      32,    44,    17,    25,    13,    85,    18,    27,    28,    19,
      68,    52,    15,    11,    27,    28,     1,     2,    70,    71,
      12,    72,    73,    74,    75,    86,    29,   106,    30,    82,
      90,    92,    25,    29,    76,    30,    31,    43,    77,   104,
      26,    85,   118,    31,     1,     2,    49,   119,    27,    28,
      50,   107,    27,    28,     1,     2,    70,    71,    42,    72,
      73,    74,    75,    18,    21,    82,    19,    29,    43,    30,
      89,    29,    76,    30,   121,    43,   113,    31,     8,     5,
      45,    31,    10,     1,     2,     1,     2,   134,   135,   123,
     124,   125,    85,    85,   139,    61,    62,   126,   142,    85,
     128,    27,    28,    85,    46,    70,    71,    47,    72,    73,
      74,    75,    48,   136,    27,    28,    64,    65,    66,   140,
      29,    76,    30,    53,    43,    54,    69,    88,    93,    94,
      31,   108,   109,    29,   110,    30,    55,    56,    57,    58,
      59,    60,   105,    31,    97,    98,    99,   100,   101,   102,
     111,   112,   115,   137,   117,   116,   122,     9,   132,   120,
      18,   130,   131,   129,   133,   138,    87,   127,   141,   114,
      16,    95,   103,    96
};

static const yytype_uint8 yycheck[] =
{
      19,    21,    24,    17,     4,    43,    28,     3,     4,    31,
      38,    30,     4,    23,     3,     4,     5,     6,     7,     8,
      30,    10,    11,    12,    13,    45,    22,    23,    24,    43,
      49,    50,    46,    22,    23,    24,    32,    26,    27,    67,
       3,    79,    25,    32,     5,     6,    24,    30,     3,     4,
      28,    70,     3,     4,     5,     6,     7,     8,    28,    10,
      11,    12,    13,    28,    25,    79,    31,    22,    26,    24,
      25,    22,    23,    24,    93,    26,    27,    32,     0,     0,
      25,    32,     3,     5,     6,     5,     6,   130,   131,   108,
     109,   110,   130,   131,   137,    32,    33,   116,   141,   137,
     119,     3,     4,   141,    30,     7,     8,     4,    10,    11,
      12,    13,    29,   132,     3,     4,    34,    35,    36,   138,
      22,    23,    24,    21,    26,    20,     3,    28,    28,    25,
      32,    24,    24,    22,    24,    24,    14,    15,    16,    17,
      18,    19,    29,    32,    55,    56,    57,    58,    59,    60,
      23,    23,    23,     9,    29,    31,    23,     3,    23,    29,
      28,    25,    25,    29,    23,    23,    46,   117,    25,    79,
      12,    53,    63,    54
};

/* YYSTOS[STATE-NUM] -- The symbol kind of the accessing symbol of
   state STATE-NUM.  */
static const yytype_int8 yystos[] =
{
       0,     5,     6,    38,    39,    48,    49,    51,     0,    39,
      48,    23,    30,     4,    50,     4,    50,    24,    28,    31,
      43,    25,    40,    41,    42,    51,     3,     3,     4,    22,
      24,    32,    53,    54,    55,    56,    57,    58,    61,    62,
      63,    65,    28,    26,    45,    25,    30,     4,    29,    24,
      28,    44,    53,    21,    20,    14,    15,    16,    17,    18,
      19,    32,    33,    59,    34,    35,    36,    60,    62,     3,
       7,     8,    10,    11,    12,    13,    23,    27,    45,    46,
      47,    48,    51,    52,    53,    65,    45,    42,    28,    25,
      53,    64,    53,    28,    25,    55,    56,    57,    57,    57,
      57,    57,    57,    58,    62,    29,    23,    53,    24,    24,
      24,    23,    23,    27,    47,    23,    31,    29,    25,    30,
      29,    53,    23,    53,    53,    53,    53,    43,    53,    29,
      25,    25,    23,    23,    52,    52,    53,     9,    23,    52,
      53,    25,    52
};

/* YYR1[RULE-NUM] -- Symbol kind of the left-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr1[] =
{
       0,    37,    38,    38,    38,    38,    39,    39,    40,    40,
      41,    41,    42,    42,    43,    43,    43,    44,    44,    45,
      45,    46,    46,    47,    47,    48,    49,    49,    50,    50,
      50,    51,    51,    52,    52,    52,    52,    52,    52,    52,
      52,    52,    52,    52,    52,    53,    54,    54,    55,    55,
      56,    56,    56,    56,    56,    56,    56,    57,    57,    58,
      58,    59,    59,    60,    60,    60,    61,    61,    62,    62,
      62,    63,    63,    63,    63,    64,    64,    65,    65
};

/* YYR2[RULE-NUM] -- Number of symbols on the right-hand side of rule RULE-NUM.  */
static const yytype_int8 yyr2[] =
{
       0,     2,     1,     1,     2,     2,     5,     6,     0,     1,
       1,     3,     2,     5,     3,     4,     0,     3,     4,     2,
       3,     1,     2,     1,     1,     2,     2,     3,     1,     2,
       3,     1,     1,     3,     2,     4,     1,     2,     1,     5,
       7,     5,     9,     2,     2,     1,     1,     3,     1,     3,
       1,     3,     3,     3,     3,     3,     3,     1,     3,     1,
       3,     1,     1,     1,     1,     1,     1,     1,     1,     3,
       4,     3,     1,     1,     2,     1,     3,     1,     2
};


enum { YYENOMEM = -2 };

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (yychar = YYEMPTY)

#define YYACCEPT        goto yyacceptlab
#define YYABORT         goto yyabortlab
#define YYERROR         goto yyerrorlab
#define YYNOMEM         goto yyexhaustedlab


#define YYRECOVERING()  (!!yyerrstatus)

#define YYBACKUP(Token, Value)                                    \
  do                                                              \
    if (yychar == YYEMPTY)                                        \
      {                                                           \
        yychar = (Token);                                         \
        yylval = (Value);                                         \
        YYPOPSTACK (yylen);                                       \
        yystate = *yyssp;                                         \
        goto yybackup;                                            \
      }                                                           \
    else                                                          \
      {                                                           \
        yyerror (YY_("syntax error: cannot back up")); \
        YYERROR;                                                  \
      }                                                           \
  while (0)

/* Backward compatibility with an undocumented macro.
   Use YYerror or YYUNDEF. */
#define YYERRCODE YYUNDEF


/* Enable debugging if requested.  */
#if YYDEBUG

# ifndef YYFPRINTF
#  include <stdio.h> /* INFRINGES ON USER NAME SPACE */
#  define YYFPRINTF fprintf
# endif

# define YYDPRINTF(Args)                        \
do {                                            \
  if (yydebug)                                  \
    YYFPRINTF Args;                             \
} while (0)




# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)                    \
do {                                                                      \
  if (yydebug)                                                            \
    {                                                                     \
      YYFPRINTF (stderr, "%s ", Title);                                   \
      yy_symbol_print (stderr,                                            \
                  Kind, Value); \
      YYFPRINTF (stderr, "\n");                                           \
    }                                                                     \
} while (0)


/*-----------------------------------.
| Print this symbol's value on YYO.  |
`-----------------------------------*/

static void
yy_symbol_value_print (FILE *yyo,
                       yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  FILE *yyoutput = yyo;
  YY_USE (yyoutput);
  if (!yyvaluep)
    return;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/*---------------------------.
| Print this symbol on YYO.  |
`---------------------------*/

static void
yy_symbol_print (FILE *yyo,
                 yysymbol_kind_t yykind, YYSTYPE const * const yyvaluep)
{
  YYFPRINTF (yyo, "%s %s (",
             yykind < YYNTOKENS ? "token" : "nterm", yysymbol_name (yykind));

  yy_symbol_value_print (yyo, yykind, yyvaluep);
  YYFPRINTF (yyo, ")");
}

/*------------------------------------------------------------------.
| yy_stack_print -- Print the state stack from its BOTTOM up to its |
| TOP (included).                                                   |
`------------------------------------------------------------------*/

static void
yy_stack_print (yy_state_t *yybottom, yy_state_t *yytop)
{
  YYFPRINTF (stderr, "Stack now");
  for (; yybottom <= yytop; yybottom++)
    {
      int yybot = *yybottom;
      YYFPRINTF (stderr, " %d", yybot);
    }
  YYFPRINTF (stderr, "\n");
}

# define YY_STACK_PRINT(Bottom, Top)                            \
do {                                                            \
  if (yydebug)                                                  \
    yy_stack_print ((Bottom), (Top));                           \
} while (0)


/*------------------------------------------------.
| Report that the YYRULE is going to be reduced.  |
`------------------------------------------------*/

static void
yy_reduce_print (yy_state_t *yyssp, YYSTYPE *yyvsp,
                 int yyrule)
{
  int yylno = yyrline[yyrule];
  int yynrhs = yyr2[yyrule];
  int yyi;
  YYFPRINTF (stderr, "Reducing stack by rule %d (line %d):\n",
             yyrule - 1, yylno);
  /* The symbols being reduced.  */
  for (yyi = 0; yyi < yynrhs; yyi++)
    {
      YYFPRINTF (stderr, "   $%d = ", yyi + 1);
      yy_symbol_print (stderr,
                       YY_ACCESSING_SYMBOL (+yyssp[yyi + 1 - yynrhs]),
                       &yyvsp[(yyi + 1) - (yynrhs)]);
      YYFPRINTF (stderr, "\n");
    }
}

# define YY_REDUCE_PRINT(Rule)          \
do {                                    \
  if (yydebug)                          \
    yy_reduce_print (yyssp, yyvsp, Rule); \
} while (0)

/* Nonzero means print parse trace.  It is left uninitialized so that
   multiple parsers can coexist.  */
int yydebug;
#else /* !YYDEBUG */
# define YYDPRINTF(Args) ((void) 0)
# define YY_SYMBOL_PRINT(Title, Kind, Value, Location)
# define YY_STACK_PRINT(Bottom, Top)
# define YY_REDUCE_PRINT(Rule)
#endif /* !YYDEBUG */


/* YYINITDEPTH -- initial size of the parser's stacks.  */
#ifndef YYINITDEPTH
# define YYINITDEPTH 200
#endif

/* YYMAXDEPTH -- maximum size the stacks can grow to (effective only
   if the built-in stack extension method is used).

   Do not make this value too large; the results are undefined if
   YYSTACK_ALLOC_MAXIMUM < YYSTACK_BYTES (YYMAXDEPTH)
   evaluated with infinite-precision integer arithmetic.  */

#ifndef YYMAXDEPTH
# define YYMAXDEPTH 10000
#endif






/*-----------------------------------------------.
| Release the memory associated to this symbol.  |
`-----------------------------------------------*/

static void
yydestruct (const char *yymsg,
            yysymbol_kind_t yykind, YYSTYPE *yyvaluep)
{
  YY_USE (yyvaluep);
  if (!yymsg)
    yymsg = "Deleting";
  YY_SYMBOL_PRINT (yymsg, yykind, yyvaluep, yylocationp);

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  YY_USE (yykind);
  YY_IGNORE_MAYBE_UNINITIALIZED_END
}


/* Lookahead token kind.  */
int yychar;

/* The semantic value of the lookahead symbol.  */
YYSTYPE yylval;
/* Number of syntax errors so far.  */
int yynerrs;




/*----------.
| yyparse.  |
`----------*/

int
yyparse (void)
{
    yy_state_fast_t yystate = 0;
    /* Number of tokens to shift before error messages enabled.  */
    int yyerrstatus = 0;

    /* Refer to the stacks through separate pointers, to allow yyoverflow
       to reallocate them elsewhere.  */

    /* Their size.  */
    YYPTRDIFF_T yystacksize = YYINITDEPTH;

    /* The state stack: array, bottom, top.  */
    yy_state_t yyssa[YYINITDEPTH];
    yy_state_t *yyss = yyssa;
    yy_state_t *yyssp = yyss;

    /* The semantic value stack: array, bottom, top.  */
    YYSTYPE yyvsa[YYINITDEPTH];
    YYSTYPE *yyvs = yyvsa;
    YYSTYPE *yyvsp = yyvs;

  int yyn;
  /* The return value of yyparse.  */
  int yyresult;
  /* Lookahead symbol kind.  */
  yysymbol_kind_t yytoken = YYSYMBOL_YYEMPTY;
  /* The variables used to return semantic value and location from the
     action routines.  */
  YYSTYPE yyval;



#define YYPOPSTACK(N)   (yyvsp -= (N), yyssp -= (N))

  /* The number of symbols on the RHS of the reduced rule.
     Keep to zero when no symbol should be popped.  */
  int yylen = 0;

  YYDPRINTF ((stderr, "Starting parse\n"));

  yychar = YYEMPTY; /* Cause a token to be read.  */

  goto yysetstate;


/*------------------------------------------------------------.
| yynewstate -- push a new state, which is found in yystate.  |
`------------------------------------------------------------*/
yynewstate:
  /* In all cases, when you get here, the value and location stacks
     have just been pushed.  So pushing a state here evens the stacks.  */
  yyssp++;


/*--------------------------------------------------------------------.
| yysetstate -- set current state (the top of the stack) to yystate.  |
`--------------------------------------------------------------------*/
yysetstate:
  YYDPRINTF ((stderr, "Entering state %d\n", yystate));
  YY_ASSERT (0 <= yystate && yystate < YYNSTATES);
  YY_IGNORE_USELESS_CAST_BEGIN
  *yyssp = YY_CAST (yy_state_t, yystate);
  YY_IGNORE_USELESS_CAST_END
  YY_STACK_PRINT (yyss, yyssp);

  if (yyss + yystacksize - 1 <= yyssp)
#if !defined yyoverflow && !defined YYSTACK_RELOCATE
    YYNOMEM;
#else
    {
      /* Get the current used size of the three stacks, in elements.  */
      YYPTRDIFF_T yysize = yyssp - yyss + 1;

# if defined yyoverflow
      {
        /* Give user a chance to reallocate the stack.  Use copies of
           these so that the &'s don't force the real ones into
           memory.  */
        yy_state_t *yyss1 = yyss;
        YYSTYPE *yyvs1 = yyvs;

        /* Each stack pointer address is followed by the size of the
           data in use in that stack, in bytes.  This used to be a
           conditional around just the two extra args, but that might
           be undefined if yyoverflow is a macro.  */
        yyoverflow (YY_("memory exhausted"),
                    &yyss1, yysize * YYSIZEOF (*yyssp),
                    &yyvs1, yysize * YYSIZEOF (*yyvsp),
                    &yystacksize);
        yyss = yyss1;
        yyvs = yyvs1;
      }
# else /* defined YYSTACK_RELOCATE */
      /* Extend the stack our own way.  */
      if (YYMAXDEPTH <= yystacksize)
        YYNOMEM;
      yystacksize *= 2;
      if (YYMAXDEPTH < yystacksize)
        yystacksize = YYMAXDEPTH;

      {
        yy_state_t *yyss1 = yyss;
        union yyalloc *yyptr =
          YY_CAST (union yyalloc *,
                   YYSTACK_ALLOC (YY_CAST (YYSIZE_T, YYSTACK_BYTES (yystacksize))));
        if (! yyptr)
          YYNOMEM;
        YYSTACK_RELOCATE (yyss_alloc, yyss);
        YYSTACK_RELOCATE (yyvs_alloc, yyvs);
#  undef YYSTACK_RELOCATE
        if (yyss1 != yyssa)
          YYSTACK_FREE (yyss1);
      }
# endif

      yyssp = yyss + yysize - 1;
      yyvsp = yyvs + yysize - 1;

      YY_IGNORE_USELESS_CAST_BEGIN
      YYDPRINTF ((stderr, "Stack size increased to %ld\n",
                  YY_CAST (long, yystacksize)));
      YY_IGNORE_USELESS_CAST_END

      if (yyss + yystacksize - 1 <= yyssp)
        YYABORT;
    }
#endif /* !defined yyoverflow && !defined YYSTACK_RELOCATE */


  if (yystate == YYFINAL)
    YYACCEPT;

  goto yybackup;


/*-----------.
| yybackup.  |
`-----------*/
yybackup:
  /* Do appropriate processing given the current state.  Read a
     lookahead token if we need one and don't already have one.  */

  /* First try to decide what to do without reference to lookahead token.  */
  yyn = yypact[yystate];
  if (yypact_value_is_default (yyn))
    goto yydefault;

  /* Not known => get a lookahead token if don't already have one.  */

  /* YYCHAR is either empty, or end-of-input, or a valid lookahead.  */
  if (yychar == YYEMPTY)
    {
      YYDPRINTF ((stderr, "Reading a token\n"));
      yychar = yylex ();
    }

  if (yychar <= YYEOF)
    {
      yychar = YYEOF;
      yytoken = YYSYMBOL_YYEOF;
      YYDPRINTF ((stderr, "Now at end of input.\n"));
    }
  else if (yychar == YYerror)
    {
      /* The scanner already issued an error message, process directly
         to error recovery.  But do not keep the error token as
         lookahead, it is too special and may lead us to an endless
         loop in error recovery. */
      yychar = YYUNDEF;
      yytoken = YYSYMBOL_YYerror;
      goto yyerrlab1;
    }
  else
    {
      yytoken = YYTRANSLATE (yychar);
      YY_SYMBOL_PRINT ("Next token is", yytoken, &yylval, &yylloc);
    }

  /* If the proper action on seeing token YYTOKEN is to reduce or to
     detect an error, take that action.  */
  yyn += yytoken;
  if (yyn < 0 || YYLAST < yyn || yycheck[yyn] != yytoken)
    goto yydefault;
  yyn = yytable[yyn];
  if (yyn <= 0)
    {
      if (yytable_value_is_error (yyn))
        goto yyerrlab;
      yyn = -yyn;
      goto yyreduce;
    }

  /* Count tokens shifted since error; after three, turn off error
     status.  */
  if (yyerrstatus)
    yyerrstatus--;

  /* Shift the lookahead token.  */
  YY_SYMBOL_PRINT ("Shifting", yytoken, &yylval, &yylloc);
  yystate = yyn;
  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END

  /* Discard the shifted token.  */
  yychar = YYEMPTY;
  goto yynewstate;


/*-----------------------------------------------------------.
| yydefault -- do the default action for the current state.  |
`-----------------------------------------------------------*/
yydefault:
  yyn = yydefact[yystate];
  if (yyn == 0)
    goto yyerrlab;
  goto yyreduce;


/*-----------------------------.
| yyreduce -- do a reduction.  |
`-----------------------------*/
yyreduce:
  /* yyn is the number of a rule to reduce with.  */
  yylen = yyr2[yyn];

  /* If YYLEN is nonzero, implement the default value of the action:
     '$$ = $1'.

     Otherwise, the following line sets YYVAL to garbage.
     This behavior is undocumented and Bison
     users should not rely upon it.  Assigning to YYVAL
     unconditionally makes the parser a bit smaller, and it avoids a
     GCC warning that YYVAL may be used uninitialized.  */
  yyval = yyvsp[1-yylen];


  YY_REDUCE_PRINT (yyn);
  switch (yyn)
    {
  case 2: /* CompileUnit: FuncDef  */
#line 83 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                      {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));

		// 设置到全局变量中
		ast_root = (yyval.node);
	}
#line 1253 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 3: /* CompileUnit: VarDecl  */
#line 91 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                  {

		// 创建一个编译单元的节点AST_OP_COMPILE_UNIT
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_COMPILE_UNIT, (yyvsp[0].node));
		ast_root = (yyval.node);
	}
#line 1264 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 4: /* CompileUnit: CompileUnit FuncDef  */
#line 97 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                              {

		// 把函数定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1274 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 5: /* CompileUnit: CompileUnit VarDecl  */
#line 102 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                              {
		// 把变量定义的节点作为编译单元的孩子
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1283 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 6: /* FuncDef: BasicType T_ID T_L_PAREN T_R_PAREN Block  */
#line 109 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                                    {
		// 函数返回类型
		type_attr funcReturnType = (yyvsp[-4].type);

		// 函数名
		var_id_attr funcId = (yyvsp[-3].var_id);

		// 函数体节点即Block，即$5
		ast_node * blockNode = (yyvsp[0].node);

		// 形参结点没有，设置为空指针
		ast_node * formalParamsNode = nullptr;

		// 创建函数定义的节点，孩子有类型，函数名，语句块和形参(实际上无)
		// create_func_def函数内会释放funcId中指向的标识符空间，切记，之后不要再释放，之前一定要是通过strdup函数或者malloc分配的空间
		(yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1305 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 7: /* FuncDef: BasicType T_ID T_L_PAREN FormalParams T_R_PAREN Block  */
#line 126 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                                                {
		// 函数返回类型
		type_attr funcReturnType = (yyvsp[-5].type);

		// 函数名
		var_id_attr funcId = (yyvsp[-4].var_id);

		// 形参节点
		ast_node * formalParamsNode = (yyvsp[-2].node);

		// 函数体节点即Block
		ast_node * blockNode = (yyvsp[0].node);

		// 创建函数定义的节点，孩子有类型，函数名，形参和语句块
		(yyval.node) = create_func_def(funcReturnType, funcId, blockNode, formalParamsNode);
	}
#line 1326 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 8: /* FormalParams: %empty  */
#line 145 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
               {
		// 空的形参列表
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS);
	}
#line 1335 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 9: /* FormalParams: FormalParamList  */
#line 149 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                          {
		// 非空形参列表
		(yyval.node) = (yyvsp[0].node);
	}
#line 1344 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 10: /* FormalParamList: FormalParam  */
#line 156 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                              {
		// 创建形参列表节点
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAMS, (yyvsp[0].node));
	}
#line 1353 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 11: /* FormalParamList: FormalParamList T_COMMA FormalParam  */
#line 160 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                              {
		// 添加形参到列表
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 1362 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 12: /* FormalParam: BasicType T_ID  */
#line 167 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                             {
		// 普通变量形参，例如: int a
		
		// 创建类型节点
		ast_node * type_node = create_type_node((yyvsp[-1].type));
		
		// 创建变量ID节点
		ast_node * id_node = ast_node::New((yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno);
		
		// 释放字符串空间
		free((yyvsp[0].var_id).id);
		
		// 创建形参节点，包含类型和ID
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAM, type_node, id_node);
	}
#line 1382 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 13: /* FormalParam: BasicType T_ID T_L_BRACKET T_R_BRACKET DimensionList  */
#line 182 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                                               {
		// 数组形参，例如: int a[][2][3]...
		
		// 创建类型节点（保持为基本类型）
		ast_node * type_node = create_type_node((yyvsp[-4].type));
		
		// 创建变量ID节点
		ast_node * id_node = ast_node::New((yyvsp[-3].var_id).id, (yyvsp[-3].var_id).lineno);
		
		// 创建第一维空标记节点（第一维大小未指定）
		ast_node * first_dim = ast_node::New(digit_int_attr{0, (yyvsp[-3].var_id).lineno});
		
		// 释放字符串空间
		free((yyvsp[-3].var_id).id);
		
		// 合并所有维度：第一维 + 后续维度列表
		ast_node * all_dims = create_contain_node(ast_operator_type::AST_OP_ARRAY_DIMENSIONS, first_dim);
		if ((yyvsp[0].node) != nullptr) {
			// 将DimensionList的所有子节点添加到all_dims中
			for (auto child : (yyvsp[0].node)->sons) {
				all_dims->insert_son_node(child);
			}
		}
		
		// 创建形参节点，包含类型、ID和所有维度
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_FORMAL_PARAM, type_node, id_node, all_dims);
	}
#line 1414 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 14: /* DimensionList: T_L_BRACKET T_DIGIT T_R_BRACKET  */
#line 212 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                                {
		// 单个维度
		ast_node * size_node = ast_node::New((yyvsp[-1].integer_num));
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_DIMENSIONS, size_node);
	}
#line 1424 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 15: /* DimensionList: DimensionList T_L_BRACKET T_DIGIT T_R_BRACKET  */
#line 217 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                                        {
		// 递归添加维度
		ast_node * size_node = ast_node::New((yyvsp[-1].integer_num));
		(yyval.node) = (yyvsp[-3].node)->insert_son_node(size_node);
	}
#line 1434 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 16: /* DimensionList: %empty  */
#line 222 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
          {
		// 空维度列表
		(yyval.node) = nullptr;
	}
#line 1443 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 17: /* IndexList: T_L_BRACKET Expr T_R_BRACKET  */
#line 229 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                         {
		// 单个索引
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_INDICES, (yyvsp[-1].node));
	}
#line 1452 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 18: /* IndexList: IndexList T_L_BRACKET Expr T_R_BRACKET  */
#line 233 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                                 {
		// 递归添加索引
		(yyval.node) = (yyvsp[-3].node)->insert_son_node((yyvsp[-1].node));
	}
#line 1461 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 19: /* Block: T_L_BRACE T_R_BRACE  */
#line 242 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                            {
		// 语句块没有语句

		// 为了方便创建一个空的Block节点
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_BLOCK);
	}
#line 1472 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 20: /* Block: T_L_BRACE BlockItemList T_R_BRACE  */
#line 248 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                            {
		// 语句块含有语句

		// BlockItemList归约时内部创建Block节点，并把语句加入，这里不创建Block节点
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1483 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 21: /* BlockItemList: BlockItem  */
#line 259 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                          {
		// 第一个左侧的孩子节点归约成Block节点，后续语句可持续作为孩子追加到Block节点中
		// 创建一个AST_OP_BLOCK类型的中间节点，孩子为Statement($1)
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_BLOCK, (yyvsp[0].node));
	}
#line 1493 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 22: /* BlockItemList: BlockItemList BlockItem  */
#line 264 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                  {
		// 把BlockItem归约的节点加入到BlockItemList的节点中
		(yyval.node) = (yyvsp[-1].node)->insert_son_node((yyvsp[0].node));
	}
#line 1502 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 23: /* BlockItem: Statement  */
#line 273 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                       {
		// 语句节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1511 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 24: /* BlockItem: VarDecl  */
#line 277 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                  {
		// 变量声明节点传递给归约后的节点上，综合属性
		(yyval.node) = (yyvsp[0].node);
	}
#line 1520 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 25: /* VarDecl: VarDeclExpr T_SEMICOLON  */
#line 288 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                  {
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1528 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 26: /* VarDeclExpr: BasicType VarDef  */
#line 294 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                              {

		// 创建类型节点
		ast_node * type_node = create_type_node((yyvsp[-1].type));

		// 创建变量定义节点
		ast_node * decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));
		decl_node->type = type_node->type;

		// 创建变量声明语句，并加入第一个变量
		(yyval.node) = create_var_decl_stmt_node(decl_node);
	}
#line 1545 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 27: /* VarDeclExpr: VarDeclExpr T_COMMA VarDef  */
#line 306 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                     {

		// 创建类型节点，这里从VarDeclExpr获取类型，前面已经设置
		ast_node * type_node = ast_node::New((yyvsp[-2].node)->type);

		// 创建变量定义节点
		ast_node * decl_node = create_contain_node(ast_operator_type::AST_OP_VAR_DECL, type_node, (yyvsp[0].node));

		// 插入到变量声明语句
		(yyval.node) = (yyvsp[-2].node)->insert_son_node(decl_node);
	}
#line 1561 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 28: /* VarDef: T_ID  */
#line 320 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
              {
		// 变量ID

		(yyval.node) = ast_node::New(var_id_attr{(yyvsp[0].var_id).id, (yyvsp[0].var_id).lineno});

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
	}
#line 1574 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 29: /* VarDef: T_ID DimensionList  */
#line 328 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                         {
        // 数组变量定义，支持任意维度，例如: int a[10][20][30]...
        
        // 创建变量ID节点
        ast_node* id_node = ast_node::New(var_id_attr{(yyvsp[-1].var_id).id, (yyvsp[-1].var_id).lineno});
        
        // 释放字符串空间
        free((yyvsp[-1].var_id).id);
        
        // 创建数组定义节点，包含ID和所有维度
        if ((yyvsp[0].node) != nullptr) {
            (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_DEF, id_node, (yyvsp[0].node));
        } else {
            // 如果维度列表为空，则是普通变量
            (yyval.node) = id_node;
        }
    }
#line 1596 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 30: /* VarDef: T_ID T_ASSIGN Expr  */
#line 345 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                         {
        // 变量ID及初始值

        // 创建变量ID节点
        ast_node* id_node = ast_node::New(var_id_attr{(yyvsp[-2].var_id).id, (yyvsp[-2].var_id).lineno});
        
        // 释放字符串空间
        free((yyvsp[-2].var_id).id);
        
        // 创建赋值节点，左边是ID，右边是表达式
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ASSIGN, id_node, (yyvsp[0].node));
	}
#line 1613 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 31: /* BasicType: T_INT  */
#line 360 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                 {
		(yyval.type) = (yyvsp[0].type);
	}
#line 1621 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 32: /* BasicType: T_VOID  */
#line 363 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                 {
		(yyval.type) = (yyvsp[0].type);
	}
#line 1629 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 33: /* Statement: T_RETURN Expr T_SEMICOLON  */
#line 374 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                              {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_RETURN, (yyvsp[-1].node));
    }
#line 1637 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 34: /* Statement: T_RETURN T_SEMICOLON  */
#line 377 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                           {
        // 添加空返回语句支持
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_RETURN);
    }
#line 1646 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 35: /* Statement: LVal T_ASSIGN Expr T_SEMICOLON  */
#line 381 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                     {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ASSIGN, (yyvsp[-3].node), (yyvsp[-1].node));
    }
#line 1654 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 36: /* Statement: Block  */
#line 384 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
            {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1662 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 37: /* Statement: Expr T_SEMICOLON  */
#line 387 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                       {
        (yyval.node) = (yyvsp[-1].node);
    }
#line 1670 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 38: /* Statement: T_SEMICOLON  */
#line 390 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                  {
        (yyval.node) = nullptr;
    }
#line 1678 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 39: /* Statement: T_IF T_L_PAREN Expr T_R_PAREN Statement  */
#line 394 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                              {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONDITIONAL, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1686 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 40: /* Statement: T_IF T_L_PAREN Expr T_R_PAREN Statement T_ELSE Statement  */
#line 397 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                                               {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONDITIONAL, (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1694 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 41: /* Statement: T_WHILE T_L_PAREN Expr T_R_PAREN Statement  */
#line 400 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                                 {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_LOOP, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1702 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 42: /* Statement: T_FOR T_L_PAREN Expr T_SEMICOLON Expr T_SEMICOLON Expr T_R_PAREN Statement  */
#line 403 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                                                                 {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_FOR, (yyvsp[-6].node), (yyvsp[-4].node), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1710 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 43: /* Statement: T_BREAK T_SEMICOLON  */
#line 406 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_BREAK);
    }
#line 1718 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 44: /* Statement: T_CONTINUE T_SEMICOLON  */
#line 409 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                             {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_CONTINUE);
    }
#line 1726 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 45: /* Expr: LogicalOrExp  */
#line 416 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                    {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1734 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 46: /* LogicalOrExp: LogicalAndExp  */
#line 421 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                             {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1742 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 47: /* LogicalOrExp: LogicalOrExp T_OR LogicalAndExp  */
#line 424 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                      {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_LOGICAL_OR, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1750 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 48: /* LogicalAndExp: RelExp  */
#line 429 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                       {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1758 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 49: /* LogicalAndExp: LogicalAndExp T_AND RelExp  */
#line 432 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                 {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_LOGICAL_AND, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1766 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 50: /* RelExp: AddExp  */
#line 437 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                {
        (yyval.node) = (yyvsp[0].node);
    }
#line 1774 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 51: /* RelExp: RelExp T_GT AddExp  */
#line 440 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_GT, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1782 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 52: /* RelExp: RelExp T_LT AddExp  */
#line 443 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_LT, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1790 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 53: /* RelExp: RelExp T_GE AddExp  */
#line 446 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_GE, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1798 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 54: /* RelExp: RelExp T_LE AddExp  */
#line 449 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_LE, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1806 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 55: /* RelExp: RelExp T_EQ AddExp  */
#line 452 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_EQ, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1814 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 56: /* RelExp: RelExp T_NE AddExp  */
#line 455 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                         {
        (yyval.node) = create_contain_node(ast_operator_type::AST_OP_NE, (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1822 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 57: /* AddExp: MulExp  */
#line 465 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                { (yyval.node) = (yyvsp[0].node); }
#line 1828 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 58: /* AddExp: AddExp AddOp MulExp  */
#line 466 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                          {
        (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node));
    }
#line 1836 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 59: /* MulExp: UnaryExp  */
#line 470 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                  { (yyval.node) = (yyvsp[0].node); }
#line 1842 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 60: /* MulExp: MulExp MulOp UnaryExp  */
#line 471 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                            { (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[-2].node), (yyvsp[0].node)); }
#line 1848 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 61: /* AddOp: T_ADD  */
#line 474 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
             {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_ADD;
	}
#line 1856 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 62: /* AddOp: T_SUB  */
#line 477 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                {
		(yyval.op_class) = (int)ast_operator_type::AST_OP_SUB;
	}
#line 1864 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 63: /* MulOp: T_MUL  */
#line 481 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
             { (yyval.op_class) = (int)ast_operator_type::AST_OP_MUL; }
#line 1870 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 64: /* MulOp: T_DIV  */
#line 482 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
            { (yyval.op_class) = (int)ast_operator_type::AST_OP_DIV; }
#line 1876 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 65: /* MulOp: T_MOD  */
#line 483 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
            { (yyval.op_class) = (int)ast_operator_type::AST_OP_MOD; }
#line 1882 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 66: /* UnaryOp: T_SUB  */
#line 486 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
               { (yyval.op_class) = (int)ast_operator_type::AST_OP_NEG; }
#line 1888 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 67: /* UnaryOp: T_NOT  */
#line 487 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
            { (yyval.op_class) = (int)ast_operator_type::AST_OP_NOT; }
#line 1894 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 68: /* UnaryExp: PrimaryExp  */
#line 493 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                      {
		// 基本表达式

		// 传递到归约后的UnaryExp上
		(yyval.node) = (yyvsp[0].node);
	}
#line 1905 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 69: /* UnaryExp: T_ID T_L_PAREN T_R_PAREN  */
#line 499 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                   {
		// 没有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-2].var_id).id), (yyvsp[-2].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-2].var_id).id);

		// 实参列表
		ast_node * paramListNode = nullptr;

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参为空，但函数内部会创建实参列表节点，无孩子
		(yyval.node) = create_func_call(name_node, paramListNode);

	}
#line 1926 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 70: /* UnaryExp: T_ID T_L_PAREN RealParamList T_R_PAREN  */
#line 515 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                                 {
		// 含有实参的函数调用

		// 创建函数调用名终结符节点
		ast_node * name_node = ast_node::New(std::string((yyvsp[-3].var_id).id), (yyvsp[-3].var_id).lineno);

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[-3].var_id).id);

		// 实参列表
		ast_node * paramListNode = (yyvsp[-1].node);

		// 创建函数调用节点，其孩子为被调用函数名和实参，实参不为空
		(yyval.node) = create_func_call(name_node, paramListNode);
	}
#line 1946 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 71: /* PrimaryExp: T_L_PAREN Expr T_R_PAREN  */
#line 534 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                       {
		// 带有括号的表达式
		(yyval.node) = (yyvsp[-1].node);
	}
#line 1955 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 72: /* PrimaryExp: T_DIGIT  */
#line 538 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                  {
        	// 无符号整型字面量

		// 创建一个无符号整型的终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].integer_num));
	}
#line 1966 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 73: /* PrimaryExp: LVal  */
#line 544 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                {
		// 具有左值的表达式

		// 直接传递到归约后的非终结符号PrimaryExp
		(yyval.node) = (yyvsp[0].node);
	}
#line 1977 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 74: /* PrimaryExp: UnaryOp UnaryExp  */
#line 550 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                             {
        (yyval.node) = create_contain_node(ast_operator_type((yyvsp[-1].op_class)), (yyvsp[0].node));
    }
#line 1985 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 75: /* RealParamList: Expr  */
#line 559 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                     {
		// 创建实参列表节点，并把当前的Expr节点加入
		(yyval.node) = create_contain_node(ast_operator_type::AST_OP_FUNC_REAL_PARAMS, (yyvsp[0].node));
	}
#line 1994 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 76: /* RealParamList: RealParamList T_COMMA Expr  */
#line 563 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                                     {
		// 左递归增加实参表达式
		(yyval.node) = (yyvsp[-2].node)->insert_son_node((yyvsp[0].node));
	}
#line 2003 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 77: /* LVal: T_ID  */
#line 570 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
            {
		// 变量名终结符

		// 创建变量名终结符节点
		(yyval.node) = ast_node::New((yyvsp[0].var_id));

		// 对于字符型字面量的字符串空间需要释放，因词法用到了strdup进行了字符串复制
		free((yyvsp[0].var_id).id);
	}
#line 2017 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;

  case 78: /* LVal: T_ID IndexList  */
#line 579 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"
                     {
        // 数组元素访问，支持任意维度，例如: a[i][j][k]...
        
        // 创建变量名节点
        ast_node* id_node = ast_node::New((yyvsp[-1].var_id));
        
        // 释放字符串空间
        free((yyvsp[-1].var_id).id);
        
        // 创建数组访问节点，包含ID和所有索引
        if ((yyvsp[0].node) != nullptr) {
            (yyval.node) = create_contain_node(ast_operator_type::AST_OP_ARRAY_ACCESS, id_node, (yyvsp[0].node));
        } else {
            // 如果没有索引，则是普通变量
            (yyval.node) = id_node;
        }
    }
#line 2039 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"
    break;


#line 2043 "/home/code/exp04-minic-expr-3/frontend/flexbison/autogenerated/MiniCBison.cpp"

      default: break;
    }
  /* User semantic actions sometimes alter yychar, and that requires
     that yytoken be updated with the new translation.  We take the
     approach of translating immediately before every use of yytoken.
     One alternative is translating here after every semantic action,
     but that translation would be missed if the semantic action invokes
     YYABORT, YYACCEPT, or YYERROR immediately after altering yychar or
     if it invokes YYBACKUP.  In the case of YYABORT or YYACCEPT, an
     incorrect destructor might then be invoked immediately.  In the
     case of YYERROR or YYBACKUP, subsequent parser actions might lead
     to an incorrect destructor call or verbose syntax error message
     before the lookahead is translated.  */
  YY_SYMBOL_PRINT ("-> $$ =", YY_CAST (yysymbol_kind_t, yyr1[yyn]), &yyval, &yyloc);

  YYPOPSTACK (yylen);
  yylen = 0;

  *++yyvsp = yyval;

  /* Now 'shift' the result of the reduction.  Determine what state
     that goes to, based on the state we popped back to and the rule
     number reduced by.  */
  {
    const int yylhs = yyr1[yyn] - YYNTOKENS;
    const int yyi = yypgoto[yylhs] + *yyssp;
    yystate = (0 <= yyi && yyi <= YYLAST && yycheck[yyi] == *yyssp
               ? yytable[yyi]
               : yydefgoto[yylhs]);
  }

  goto yynewstate;


/*--------------------------------------.
| yyerrlab -- here on detecting error.  |
`--------------------------------------*/
yyerrlab:
  /* Make sure we have latest lookahead translation.  See comments at
     user semantic actions for why this is necessary.  */
  yytoken = yychar == YYEMPTY ? YYSYMBOL_YYEMPTY : YYTRANSLATE (yychar);
  /* If not already recovering from an error, report this error.  */
  if (!yyerrstatus)
    {
      ++yynerrs;
      yyerror (YY_("syntax error"));
    }

  if (yyerrstatus == 3)
    {
      /* If just tried and failed to reuse lookahead token after an
         error, discard it.  */

      if (yychar <= YYEOF)
        {
          /* Return failure if at end of input.  */
          if (yychar == YYEOF)
            YYABORT;
        }
      else
        {
          yydestruct ("Error: discarding",
                      yytoken, &yylval);
          yychar = YYEMPTY;
        }
    }

  /* Else will try to reuse lookahead token after shifting the error
     token.  */
  goto yyerrlab1;


/*---------------------------------------------------.
| yyerrorlab -- error raised explicitly by YYERROR.  |
`---------------------------------------------------*/
yyerrorlab:
  /* Pacify compilers when the user code never invokes YYERROR and the
     label yyerrorlab therefore never appears in user code.  */
  if (0)
    YYERROR;
  ++yynerrs;

  /* Do not reclaim the symbols of the rule whose action triggered
     this YYERROR.  */
  YYPOPSTACK (yylen);
  yylen = 0;
  YY_STACK_PRINT (yyss, yyssp);
  yystate = *yyssp;
  goto yyerrlab1;


/*-------------------------------------------------------------.
| yyerrlab1 -- common code for both syntax error and YYERROR.  |
`-------------------------------------------------------------*/
yyerrlab1:
  yyerrstatus = 3;      /* Each real token shifted decrements this.  */

  /* Pop stack until we find a state that shifts the error token.  */
  for (;;)
    {
      yyn = yypact[yystate];
      if (!yypact_value_is_default (yyn))
        {
          yyn += YYSYMBOL_YYerror;
          if (0 <= yyn && yyn <= YYLAST && yycheck[yyn] == YYSYMBOL_YYerror)
            {
              yyn = yytable[yyn];
              if (0 < yyn)
                break;
            }
        }

      /* Pop the current state because it cannot handle the error token.  */
      if (yyssp == yyss)
        YYABORT;


      yydestruct ("Error: popping",
                  YY_ACCESSING_SYMBOL (yystate), yyvsp);
      YYPOPSTACK (1);
      yystate = *yyssp;
      YY_STACK_PRINT (yyss, yyssp);
    }

  YY_IGNORE_MAYBE_UNINITIALIZED_BEGIN
  *++yyvsp = yylval;
  YY_IGNORE_MAYBE_UNINITIALIZED_END


  /* Shift the error token.  */
  YY_SYMBOL_PRINT ("Shifting", YY_ACCESSING_SYMBOL (yyn), yyvsp, yylsp);

  yystate = yyn;
  goto yynewstate;


/*-------------------------------------.
| yyacceptlab -- YYACCEPT comes here.  |
`-------------------------------------*/
yyacceptlab:
  yyresult = 0;
  goto yyreturnlab;


/*-----------------------------------.
| yyabortlab -- YYABORT comes here.  |
`-----------------------------------*/
yyabortlab:
  yyresult = 1;
  goto yyreturnlab;


/*-----------------------------------------------------------.
| yyexhaustedlab -- YYNOMEM (memory exhaustion) comes here.  |
`-----------------------------------------------------------*/
yyexhaustedlab:
  yyerror (YY_("memory exhausted"));
  yyresult = 2;
  goto yyreturnlab;


/*----------------------------------------------------------.
| yyreturnlab -- parsing is finished, clean up and return.  |
`----------------------------------------------------------*/
yyreturnlab:
  if (yychar != YYEMPTY)
    {
      /* Make sure we have latest lookahead translation.  See comments at
         user semantic actions for why this is necessary.  */
      yytoken = YYTRANSLATE (yychar);
      yydestruct ("Cleanup: discarding lookahead",
                  yytoken, &yylval);
    }
  /* Do not reclaim the symbols of the rule whose action triggered
     this YYABORT or YYACCEPT.  */
  YYPOPSTACK (yylen);
  YY_STACK_PRINT (yyss, yyssp);
  while (yyssp != yyss)
    {
      yydestruct ("Cleanup: popping",
                  YY_ACCESSING_SYMBOL (+*yyssp), yyvsp);
      YYPOPSTACK (1);
    }
#ifndef yyoverflow
  if (yyss != yyssa)
    YYSTACK_FREE (yyss);
#endif

  return yyresult;
}

#line 598 "/home/code/exp04-minic-expr-3/frontend/flexbison/MiniC.y"



// 语法识别错误要调用函数的定义
void yyerror(char * msg)
{
    printf("Line %d: %s\n", yylineno, msg);
}



